### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rawpie2** [boyonk913/music-sync#1]
Exception caught from launcher
java.lang.RuntimeException: Error creating Mixin config mixins/music_sync.client.mixins.json for mod music_sync
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:96)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config mixins/music_sync.client.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94)
	... 6 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'mixins/music_sync.client.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 9 more
Exiting with ERROR

**Comment by boyonk913** [comment]
Hi!

This was a stupid mistake I made on my end.
It should be resolved as of version 1.3, which is available for Minecraft 1.16-1.20.6.

Thanks for the report. I would not have caught this without you!
